name: Go

on:
  push:
    branches: [ main ]
    paths:
      - 'go_tasks/test-go-backend-task-manager/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Run Tests
        run: go test -v ./test-go-backend-task-manager/Tests/...
