name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache Go dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Test Controllers
      run: go test -v ./Tests/controller_test.go

    - name: Test JWT Service
      run: go test -v ./Tests/jwt_service_test.go

    - name: Test Password Service
      run: go test -v ./Tests/password_service_test.go

    - name: Test Task Usecase
      run: go test -v ./Tests/task_usecase_test.go

    - name: Test User Usecase
      run: go test -v ./Tests/user_usecase_test.go
